//
// This source file is part of the Stanford Spezi open-source project
//
// SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

import Foundation
import SpeziFoundation
import SpeziViews
import SwiftUI


private struct DisplayView: DataDisplayView {
    private var phoneNumbers: [String]
    
    var body: some View {
        EmptyView()
    }
    
    init(_ value: [String]) {
        self.phoneNumbers = value
    }
}

private struct EntryView: DataEntryView {
    @Binding private var value: [String]
    
    var body: some View {
        EmptyView()
    }
    
    init(_ value: Binding<[String]>) {
        self._value = value
    }
}


extension AccountDetails {
#if compiler(<6)
    // In older compilers, we get a circular reference error when trying to add an extension (see end of file) to a type that is generated by a macro
    // Therefore, we manually expand the macro for older versions of the compiler.

    public struct __Key_phoneNumbers: AccountKey { // swiftlint:disable:this type_name
        public typealias Value = [String]

        public static let name = LocalizedStringResource("PHONE_NUMBERS", bundle: .atURL(from: .module))
        public static let identifier = "phoneNumbers"
        public static let category: AccountKeyCategory = .other
    }
#endif

#if compiler(>=6)
    public typealias PhoneNumbersArray = [String]

    /// The phone numbers of a user.
    @AccountKey(
        name: LocalizedStringResource("PHONE_NUMBERS", bundle: .atURL(from: .module)),
        as: PhoneNumbersArray.self,
        displayView: DisplayView.self,
        entryView: EntryView.self
    )
    public var phoneNumbers: PhoneNumbersArray?
#else
    /// The phone number of a user.
    public var phoneNumbers: PhoneNumbersArray? {
        get {
            self [__Key_phoneNumbers.self]
        }
        set {
            self [__Key_phoneNumbers.self] = newValue
        }
    }
#endif
}


@KeyEntry(\.phoneNumbers)
public extension AccountKeys {} // swiftlint:disable:this no_extension_access_modifier
