#
# This source file is part of the Spezi open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test Swift Package
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziAccount
      artifactname: SpeziAccount.xcresult
      resultBundle: SpeziAccount.xcresult
  buildandtest_latest:
    name: Build and Test Swift Package iOS Latest
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziAccount
      xcodeversion: latest
      swiftVersion: 6
      artifactname: SpeziAccount-Latest.xcresult
      resultBundle: SpeziAccount-Latest.xcresult
  buildandtestuitests:
    name: Build and Test UI Tests
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      artifactname: TestApp.xcresult
      resultBundle: TestApp.xcresult
  buildandtestuitests_latest:
    name: Build and Test UI Tests Latest
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      xcodeversion: latest
      swiftVersion: 6
      artifactname: TestApp-Latest.xcresult
      resultBundle: TestApp-Latest.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest, buildandtestuitests]
    uses: StanfordSpezi/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziAccount.xcresult TestApp.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
