#
# This source file is part of the Spezi open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest_ios:
    name: Build and Test Swift Package
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziAccount
      artifactname: SpeziAccount.xcresult
      resultBundle: SpeziAccount.xcresult
  buildandtest_macos:
    name: Build and Test Swift Package macOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziAccount
      destination: 'platform=macOS,arch=arm64'
      artifactname: SpeziAccount-macOS.xcresult
      resultBundle: SpeziAccount-macOS.xcresult
  buildandtest_ios_latest:
    name: Build and Test Swift Package iOS Latest
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziAccount
      xcodeversion: latest
      swiftVersion: 6
      artifactname: SpeziAccount-Latest.xcresult
      resultBundle: SpeziAccount-Latest.xcresult
  buildandtest_visionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziAccount
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: SpeziAccount-visionOS.xcresult
      artifactname: SpeziAccount-visionOS.xcresult
  buildandtestuitests_ios:
    name: Build and Test UI Tests
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      artifactname: TestApp-iOS.xcresult
      resultBundle: TestApp-iOS.xcresult
  buildandtestuitests_ios_latest:
    name: Build and Test UI Tests Latest
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      xcodeversion: latest
      swiftVersion: 6
      artifactname: TestApp-iOS-Latest.xcresult
      resultBundle: TestApp-iOS-Latest.xcresult
  buildandtestuitests_visionos:
    name: Build and Test UI Tests visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: Tests/UITests
      scheme: TestApp
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: TestApp-visionOS.xcresult
      artifactname: TestApp-visionOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest_ios, buildandtest_macos, buildandtest_visionos, buildandtestuitests_ios, buildandtestuitests_visionos]
    uses: StanfordSpezi/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziAccount.xcresult SpeziAccount-macOS.xcresult SpeziAccount-visionOS.xcresult TestApp-iOS.xcresult TestApp-visionOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
